<a href="https://colab.research.google.com/github/Nermeen-Moussa/ML-DL-Reference-Guide/blob/main/Churn_Customer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
df_train=pd.read_csv('/content/drive/MyDrive/churn/train.csv')
df_test=pd.read_csv('/content/drive/MyDrive/churn/test.csv')
df_train.head(10)

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,15617156.0,Chia,593.0,France,Male,46.0,9.0,0.00,2.0,1.0,1.0,83629.60,0.0
1,1,15607988.0,Yeh,539.0,France,Female,33.0,3.0,0.00,2.0,0.0,1.0,73979.86,0.0
2,2,15626383.0,Ch'ien,709.0,Spain,Male,21.0,2.0,0.00,2.0,0.0,1.0,25669.10,0.0
3,3,15583392.0,Palerma,628.0,Germany,Female,33.0,4.0,109342.82,1.0,1.0,1.0,67611.36,0.0
4,4,15775300.0,Palerma,640.0,France,Male,34.0,9.0,127545.99,1.0,1.0,1.0,147545.65,0.0
5,5,15638494.0,Hsia,635.0,France,Male,47.0,3.0,0.00,1.0,1.0,0.0,73371.65,1.0
6,6,15790810.0,Pinto,546.0,Germany,Female,48.0,8.0,100565.94,1.0,1.0,1.0,151843.54,1.0
7,7,15716085.0,Ugorji,705.0,France,Male,39.0,7.0,0.00,1.0,1.0,1.0,119333.95,0.0
8,8,15679294.0,K'ung,757.0,France,Male,42.0,2.0,143930.92,1.0,1.0,1.0,156660.21,0.0
9,9,15584776.0,McLean,661.0,France,Male,39.0,6.0,0.00,2.0,1.0,0.0,103557.93,0.0

In [3]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               15000 non-null  int64
 1   CustomerId       15000 non-null  float64
 2   Surname          15000 non-null  object
 3   CreditScore      15000 non-null  float64
 4   Geography        15000 non-null  object
 5   Gender           15000 non-null  object
 6   Age              15000 non-null  float64
 7   Tenure           15000 non-null  float64
 8   Balance          15000 non-null  float64
 9   NumOfProducts    15000 non-null  float64
 10  HasCrCard        15000 non-null  float64
 11  IsActiveMember   15000 non-null  float64
 12  EstimatedSalary  15000 non-null  float64
 13  Exited           15000 non-null  float64
dtypes: float64(10), int64(1), object(3)
memory usage: 1.6+ MB

In [4]:
df_train.isnull().sum()

id                 0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df_train.duplicated().sum()

np.int64(0)

In [8]:
df_train.drop(columns=['CustomerId','id'],inplace=True)
df_test.drop(columns=['CustomerId','id'],inplace=True)
df_train.head()

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Chia,593.0,France,Male,46.0,9.0,0.00,2.0,1.0,1.0,83629.60,0.0
1,Yeh,539.0,France,Female,33.0,3.0,0.00,2.0,0.0,1.0,73979.86,0.0
2,Ch'ien,709.0,Spain,Male,21.0,2.0,0.00,2.0,0.0,1.0,25669.10,0.0
3,Palerma,628.0,Germany,Female,33.0,4.0,109342.82,1.0,1.0,1.0,67611.36,0.0
4,Palerma,640.0,France,Male,34.0,9.0,127545.99,1.0,1.0,1.0,147545.65,0.0

In [18]:
df_train['Gender'].unique()

<IntegerArray>
[<NA>]
Length: 1, dtype: Int64

In [22]:
print(df_train['Gender'].value_counts(dropna=False))

Gender
<NA>    15000
Name: count, dtype: Int64

In [30]:
# Map integer/numeric keys instead of string keys
df_train['Gender'] = df_train['Gender'].map({0: 1, 1: 2})
df_test['Gender'] = df_test['Gender'].map({0: 1, 1: 2})

In [32]:
# Keep NaNs/missing values safe using Int64
df_train['Gender'] = df_train['Gender'].astype('Int64')
df_test['Gender'] = df_test['Gender'].astype('Int64')
df_train.head(20)

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Chia,593.0,France,1,46.0,9.0,0.00,2.0,1.0,1.0,83629.60,0.0
1,Yeh,539.0,France,1,33.0,3.0,0.00,2.0,0.0,1.0,73979.86,0.0
2,Ch'ien,709.0,Spain,1,21.0,2.0,0.00,2.0,0.0,1.0,25669.10,0.0
3,Palerma,628.0,Germany,1,33.0,4.0,109342.82,1.0,1.0,1.0,67611.36,0.0
4,Palerma,640.0,France,1,34.0,9.0,127545.99,1.0,1.0,1.0,147545.65,0.0
5,Hsia,635.0,France,1,47.0,3.0,0.00,1.0,1.0,0.0,73371.65,1.0
6,Pinto,546.0,Germany,1,48.0,8.0,100565.94,1.0,1.0,1.0,151843.54,1.0
7,Ugorji,705.0,France,1,39.0,7.0,0.00,1.0,1.0,1.0,119333.95,0.0
8,K'ung,757.0,France,1,42.0,2.0,143930.92,1.0,1.0,1.0,156660.21,0.0
9,McLean,661.0,France,1,39.0,6.0,0.00,2.0,1.0,0.0,103557.93,0.0
10,Ch'eng,686.0,France,1,30.0,2.0,0.00,2.0,0.0,0.0,175070.94,0.0
11,Mazzanti,745.0,France,1,35.0,6.0,0.00,2.0,0.0,1.0,90858.96,0.0
12,White,553.0,France,1,34.0,1.0,132746.20,1.0,1.0,0.0,123982.14,0.0
13,Tseng,675.0,France,1,30.0,9.0,0.00,2.0,1.0,0.0,124489.88,0.0
14,Hsueh,544.0,France,1,39.0,8.0,0.00,1.0,1.0,0.0,124429.19,0.0
15,Chin,713.0,Spain,1,28.0,3.0,0.00,2.0,0.0,1.0,152790.92,0.0
16,Chukwudi,627.0,France,1,38.0,3.0,0.00,2.0,1.0,0.0,91574.92,0.0
17,Diggs,749.0,France,1,36.0,9.0,98567.10,2.0,1.0,0.0,101866.39,0.0
18,Chidubem,692.0,France,1,47.0,5.0,0.00,1.0,1.0,1.0,105599.66,0.0
19,Yobachukwu,556.0,France,1,58.0,7.0,105795.90,1.0,1.0,1.0,35450.53,0.0

In [35]:
df_train['Geography'].unique()
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df_train['Geography']=le.fit_transform(df_train['Geography'])
df_test['Geography']=le.fit_transform(df_test['Geography'])
df_train.head(10)

,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,Chia,593.0,0,1,46.0,9.0,0.00,2.0,1.0,1.0,83629.60,0.0
1,Yeh,539.0,0,1,33.0,3.0,0.00,2.0,0.0,1.0,73979.86,0.0
2,Ch'ien,709.0,2,1,21.0,2.0,0.00,2.0,0.0,1.0,25669.10,0.0
3,Palerma,628.0,1,1,33.0,4.0,109342.82,1.0,1.0,1.0,67611.36,0.0
4,Palerma,640.0,0,1,34.0,9.0,127545.99,1.0,1.0,1.0,147545.65,0.0
5,Hsia,635.0,0,1,47.0,3.0,0.00,1.0,1.0,0.0,73371.65,1.0
6,Pinto,546.0,1,1,48.0,8.0,100565.94,1.0,1.0,1.0,151843.54,1.0
7,Ugorji,705.0,0,1,39.0,7.0,0.00,1.0,1.0,1.0,119333.95,0.0
8,K'ung,757.0,0,1,42.0,2.0,143930.92,1.0,1.0,1.0,156660.21,0.0
9,McLean,661.0,0,1,39.0,6.0,0.00,2.0,1.0,0.0,103557.93,0.0

In [36]:
df_train['Surname'].unique()

array(['Chia', 'Yeh', "Ch'ien", 'Palerma', 'Hsia', 'Pinto', 'Ugorji',
       "K'ung", 'McLean', "Ch'eng", 'Mazzanti', 'White', 'Tseng', 'Hsueh',
       'Chin', 'Chukwudi', 'Diggs', 'Chidubem', 'Yobachukwu', 'Chidiegwu',
       'Bibi', 'Hsu', 'H?', 'Y?an', 'Chiganu', 'Maclean', "T'ien",
       'Onyeorulu', 'Yobanna', 'Smith', 'Chu', "Ch'en", "Ch'in",
       'Hargrave', 'Manna', 'Chiawuotu', 'Thompson', 'Liao', 'Chinedum',
       'Chineze', 'Chinweuba', 'Nnachetam', 'Chiang', 'Onyekachi',
       'Nucci', 'Uspenskaya', 'Udinese', 'Obialo', 'Ugochukwu',
       'Chikezie', "Ch'iu", 'Iloerika', 'Y?', 'Cawthorne', 'Hsieh', 'Kao',
       'Dickson', "Ts'ui", 'Udegbunam', 'Brown', 'Lassetter',
       'Illingworth', 'Chinomso', 'Nwachukwu', 'Nnonso', 'Burdekin',
       'Ritchie', 'Ugoji', 'Genovese', 'Yefremov', 'Chien', 'Mazzi',
       'Trevisan', 'Chukwubuikem', 'Uchenna', 'Cremonesi', 'Nkemjika',
       'Chukwukere', 'Houghton', 'Chukwufumnanya', 'Macleod',
       'Chukwuemeka', "Ts'ai", 'Onwuamaeze', 'Tien', 'Bazarova', 'Hs?',
       'Eluemuno', "P'eng", 'Uvarov', 'Lucchese', 'Whitelegge', 'Martin',
       'Chidimma', 'Chukwualuka', 'Lettiere', 'Fanucci', 'Dyer',
       'Okwudiliolisa', 'L?', 'Onwuamaegbu', 'Bellucci', 'Okagbue',
       'Lucciano', 'Mamelu', 'Onyemauchechukwu', 'Rizzo', 'Chukwuebuka',
       'Tsou', 'Okwuoma', "Ch'ang", 'Ngozichukwuka', 'Zito', 'Chikelu',
       'Yudina', 'Lo', 'Chibuzo', 'Scott', 'Nwankwo', 'Chidi',
       'Calabresi', 'Shih', 'Wright', 'Lu', 'Chiu', 'Black', 'Kornilova',
       'Nwabugwu', 'Nnamdi', 'Hsing', 'Efremov', 'Pagnotto', 'Moseley',
       'Teng', 'Chukwujamuike', 'Lai', 'Genovesi', 'Hs?eh', 'Fiorentini',
       'Clements', 'Okwudilichukwu', 'Obijiaku', 'Chinwendu', 'Ibeamaka',
       'Nnamutaezinwa', 'Onyemere', 'Chiekwugo', 'Trevisano', 'Ozioma',
       'Trevisani', 'Nnaife', 'Hsiung', 'Pisani', 'Chuang', 'Folliero',
       'Hao', 'Ojiofor', 'Milani', 'Pirozzi', 'Tung', "T'ao",
       'Tretiakova', 'Yefimova', 'Ukaegbunam', 'K?', 'Hsiao', 'Farrar',
       'Chikwado', 'Zhirov', 'Chiemenam', 'Onyemachukwu', 'Mancini',
       'Cattaneo', 'McElhone', 'Macartney', 'Onwudiwe', 'Li Fonti',
       'Onio', 'Chibugo', 'Mackay', 'Chifley', 'Nwokike', 'Yao',
       'Onyinyechukwuka', 'Biryukov', 'Bancks', 'Chiedozie', 'Goliwe',
       'Lo Duca', 'Chibueze', 'Blesing', 'Isoomelum', 'Tuan', 'Yocum',
       'Nwokezuike', 'Milne', 'Iqbal', 'Palermo', 'Chiagoziem', 'Pisano',
       'Udinesi', 'Hargreaves', 'Ebelegbulam', 'Chiebuka', 'Tsao',
       'McIntosh', 'Raff', 'Iweobiegbulam', 'Chidumaga', 'Kenechukwu',
       'Mironova', 'Shao', 'Frolov', 'De Neeve', 'Ugochukwutubelum',
       "O'Loghlen", 'Iadanza', 'Olisanugo', 'Johnson', 'Chiazagomekpere',
       'Pugh', 'Chizuoke', 'Obiajulu', 'Naylor', 'Chukwueloka', 'Toscani',
       'Chukwumaobim', 'Yancy', 'Nkemakonam', 'Gartrell', 'Bischof',
       "O'Brien", 'Zaytseva', 'Chijindum', 'Yefremova', 'Ikedinachukwu',
       'Chukwukadibia', 'Miah', 'Onuchukwu', 'Fokina', 'Chiemezie',
       'Onwumelu', 'Chiemeka', 'Aiken', 'Nkemakolam', 'Fomin',
       'Zikoranachidimma', 'Yermakov', 'Chiemela', 'Greco', 'Nebechukwu',
       'Young', 'Onuoha', 'Nkemdilim', 'Hughes', 'Milanesi', 'Okoli',
       "Ts'ao", "T'ang", 'Aksenov', 'Ponce', "O'Loughlin", 'Aitken',
       'Brownless', 'Ozerova', 'Nwora', 'Loewenthal', 'Yevseyev',
       'Uwakwe', 'Milano', 'Kaeppel', 'McIntyre', 'Wan', 'Niu', 'Tipton',
       'Kumm', 'Calabrese', 'DeRose', 'Nwoye', 'Ting', 'Yermolayeva',
       'Fiorentino', 'Yermolayev', 'Aksakova', 'Chienezie', 'King',
       'Kerr', 'Shubina', 'Chukwuhaenye', 'Johnstone', 'Ozoemena',
       'Oguejiofor', "O'Neill", 'Chukwujekwu', 'Yuriev', 'Ejimofor',
       'Monds', 'Yashina', 'Nnabuife', 'Ponomarev', 'De Bernales',
       'Padovesi', 'Ives', 'Ruse', 'Shcherbakov', 'De Luca', 'Ukaegbulam',
       'Galkin', 'Oluchukwu', 'Chukwuma', 'Lung', 'Graham', 'Udegbulam',
       'Hales', 'Brierly', 'Ndubueze', 'Nwachinemelu', 'Olisaemeka',
       'Maughan', 'Chinwenma', 'Yermakova', 'Fane', 'Ma', 'Uchechukwu',
       'Chidiebere', 'Ulyanova', 'Yefimov', 'Hixson', "O'Donnell",
       'Moore', 'Zetticci', 'Linton', 'Iheanacho', 'Chiazagomekpele',
       'Onyekaozulu', "P'an", 'Baddeley', 'Okeke', 'Echezonachukwu',
       'Lombardo', "T'an", 'Ijendu', 'Horsley', 'Grosse', 'Walker', 'Fan',
       'Chimezie', 'Pino', 'Obielumani', 'Ebelechukwu', 'Kosisochukwu',
       'Fyodorov', 'Onyekachukwu', 'Onochie', 'Mistry', 'Iweobiegbunam',
       'Chinwemma', 'Okwuadigbo', 'Yobachi', 'Uwaezuoke', 'Burtch',
       'Whitehouse', 'Okonkwo', 'Bovee', "O'Sullivan", 'Boulger',
       'Whitehead', 'Nworie', 'Yevdokimova', 'Ibezimako', 'Chinonyelum',
       'Tikhonov', 'Cawood', 'Bage', 'Kenechi', 'Kesteven', 'Wei',
       'Yuryeva', 'Baresi', 'Tsai', 'Nkemdirim', 'Lucchesi', 'Zuyev',
       'Kuo', 'Chizoba', 'Onuora', 'Luffman', 'Balsillie', 'Padovano',
       'Chung', 'Kepley', 'Trentino', 'Ku', "O'Callaghan", 'Ochoa',
       'Aksyonova', 'McGregor', 'Obiora', 'Chigozie', 'Okechukwu',
       'Uvarova', 'Chialuka', 'Chidozie', 'Pye', 'Bitter', 'Uspensky',
       'Udokamma', 'Watson', 'Achebe', 'Li', 'Kable', 'Nweke', 'Nnanna',
       'Gboliwe', 'Chigbogu', 'McMillan', 'Fenton', 'Feng', 'Chinweike',
       'Liardet', 'Gadsdon', 'Sun', 'Macdonald', 'Onwuemelie', 'Chigolum',
       'Yudin', 'Frolova', 'Fang', 'Zuyeva', 'Omeokachie', 'Dike',
       'Onyeoruru', 'Chinagorom', 'Pipes', 'Ewing', 'Kincaid', 'Ginn',
       'Aksyonov', 'Gannon', 'Okorie', 'Iheatu', 'Knepper', 'Buchi',
       'Obidimkpa', 'Sievier', 'Fennell', 'Obinna', 'Nieves',
       'Onyenachiya', 'Ogochukwu', 'Biryukova', 'Krichauff', 'Tretiakov',
       'Galkina', 'Dominguez', 'Kuznetsova', 'Pendergrass',
       'Ugonnatubelum', 'Chidiebele', 'Koo', 'Fetherstonhaugh',
       'Ponomaryova', 'Chieloka', 'Napolitano', 'Kambinachi', 'Chuter',
       'Bock', 'Nwebube', 'Lombardi', 'Golubeva', 'Kaur', 'Fink',
       'Rowntree', 'Okwukwe', 'Skelton', 'Pankhurst', 'Ndukaku',
       'Kashiwagi', 'Yegorova', 'Thomson', 'Babbage', 'Onyemauchechi',
       'Kudryashova', 'Oluchi', 'Chijioke', 'Binder', 'Laidley', 'Mao',
       'Hazon', 'Horsfall', 'Chubb', 'Ubanwa', 'Gresswell', 'Onwughara',
       'McFarland', 'Sagese', 'Ifeajuna', 'Chimaobim', 'Rippey',
       'Udobata', 'Hodge', 'Ndubuagha', 'Nwokeocha', 'Onwubiko', 'Bogle',
       'McElyea', 'Shen', 'Chikere', 'Piazza', 'Sells', "O'Meara",
       'Ahern', 'Boni', 'Fisk', 'Romani', 'Tardent', 'Hill', 'Chimaoke',
       'She', 'Mollison', 'Efimov', 'Wilson', 'Bess', 'Sacco',
       'Nwagugheuzo', 'Gorman', 'Fyodorova', 'Bell', 'Estrada',
       "O'Loghlin", 'Baryshnikov', 'Groom', 'Hovell', 'Bancroft',
       'Eiland', 'Riggs', 'Burns', 'Cumbrae-Stewart', 'Ejikemeifeuwa',
       'Yegorov', 'Pape', 'Garmon', 'Dettmann', 'Eipper', 'Brient',
       'Jamieson', 'Chioke', 'Mai', 'Deleon', 'Muecke', 'Bradley',
       'Debellis', 'Ponomaryov', 'Erskine', 'Huddart', 'Hunter',
       'Nebechi', 'Frewin', 'Nnaemeka', 'Macintyre', 'Gaffney',
       'Krawczyk', 'Haddon', 'Marshall', 'Kolesnikov', "P.O'Meara",
       'Hightower', 'Fokine', 'Rolon', 'Gadsden', 'Creswell', 'Iloabuchi',
       'Logue', 'Iredale', 'Golubev', 'Wang', 'Hoolan', 'Burt',
       'Titheradge', 'Lupton', 'Hinton', 'Akhtar', 'Akabueze',
       'Kuykendall', 'Kisch', 'Onodugoadiegbemma', 'Harker', 'Ulyanov',
       'Chidalu', 'Aikenhead', 'Shubin', 'Pethard', 'McWilliam', 'Ni',
       'Cavenagh', 'Bales', 'Gebhart', 'Mackey', 'Chikwendu', 'Dufresne',
       'Bledsoe', 'Sazonova', 'Napolitani', 'Lira', 'Yirawala', 'McEwan',
       "O'Toole", 'Mault', 'Trejo', 'Aksenova', 'Maccallum', 'MacDevitt',
       'Ruggiero', 'Kibby', 'McEncroe', 'Cairns', 'Hirst', 'De Garis',
       'Grieve', 'Chiabuotu', 'Dore', 'Macvitie', 'Miller', 'Bergamaschi',
       'Nwokeozie', 'McNeill', 'Fakine', 'Dennys', 'Mactier', 'Koger',
       'De Mestre', 'Liang', 'Tisdall', 'Onyemaechi', 'Maitland',
       'Rounsevell', 'Fitch', 'Fitts', 'Loyau', 'Akeroyd', 'Ibeabuchi',
       'Oster', 'Onwuatuegwu', 'Mironov', 'Rueda', 'Onwuka', 'Ross',
       'Koehler', 'Hickey', 'Nielson', 'Ainsworth', 'Tang', 'Cameron',
       'Davide', 'Wallace', 'Akobundu', 'Kennedy', 'Treacy', 'Mott',
       'Kibble', 'Shaffer', 'Ibragimova', 'Zikoranachukwudimma', 'Ko',
       'Ekechukwu', 'Nock', 'McDonald', 'Chukwuraenye', 'Fennescey',
       'De Salis', 'Lajoie', 'Nmezimako', 'Bevan', 'Lueck', 'Estep',
       'Gage', 'Crawford', 'Chukwunonso', 'Sheppard', 'Cisneros',
       'Trentini', 'McClinton', 'Paling', 'Cawker', 'Istomin', 'Fiore',
       'Gell', 'Curnow', 'Larkin', 'Mello', 'Gilleland', 'Longo',
       'MacDonnell', 'Hargraves', 'Pomeroy', 'Bufkin', 'Shand', 'Bair',
       'Molineux', 'Purdy', 'Riddle', 'Soto', 'Gough', 'Azikiwe', 'Loane',
       'Uren', 'Kline', 'Toth', 'Davison', 'Brownlow', 'Kiang', 'Yip',
       'Yost', 'Lattimore', "O'Connor", 'Rene', 'McWilliams', 'Chu Yang',
       'Zaitsev', 'Gomes', 'Pacheco', 'Macfarlan', 'Linger', 'McVey',
       'Shillito', 'Macrossan', 'Hingston', 'Wood', 'Macadam', 'Nickson',
       'Doyne', 'Sorenson', 'Avent', 'Kegley', 'McDavid', 'Chidie',
       'Lori', 'Yomina', 'Ndubuisi', 'Rishel', 'Dann', 'Foveaux',
       'Chiwetelu', 'Cribb', "O'Kane", 'Yewen', 'Gentry', 'Huggins',
       'Zuev', 'Ratten', 'Woodhouse', 'Kolesnikova', 'Gidney'],
      dtype=object)

In [46]:
df_train.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Surname_Enc
0,593.0,0,1,46.0,9.0,0.00,2.0,1.0,1.0,83629.60,0.0,0.171053
1,539.0,0,1,33.0,3.0,0.00,2.0,0.0,1.0,73979.86,0.0,0.472222
2,709.0,2,1,21.0,2.0,0.00,2.0,0.0,1.0,25669.10,0.0,0.219409
3,628.0,1,1,33.0,4.0,109342.82,1.0,1.0,1.0,67611.36,0.0,0.169492
4,640.0,0,1,34.0,9.0,127545.99,1.0,1.0,1.0,147545.65,0.0,0.169492

In [49]:
df_train['Exited'].value_counts()

Exited
0.0    11896
1.0     3104
Name: count, dtype: int64

In [53]:
X = df_train.drop(columns=['Exited', 'id'], errors='ignore')
y = df_train['Exited']
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [51]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.13/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.13/dist-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.13/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.13/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp313-cp313-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 6.0 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [54]:
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import roc_auc_score

# 1. Train LightGBM Model
lgb_model = LGBMClassifier(
    n_estimators=1000,
    learning_rate=0.03,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    verbose=-1
)
lgb_model.fit(X_train, y_train)

# 2. Train CatBoost Model
cat_model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.03,
    depth=6,
    random_seed=42,
    verbose=0
)
cat_model.fit(X_train, y_train)

# 3. Predict probabilities & calculate ROC-AUC
lgb_probs = lgb_model.predict_proba(X_val)[:, 1]
cat_probs = cat_model.predict_proba(X_val)[:, 1]
ensemble_probs = (0.5 * lgb_probs) + (0.5 * cat_probs)

print(f"LightGBM ROC-AUC: {roc_auc_score(y_val, lgb_probs):.5f}")
print(f"CatBoost ROC-AUC: {roc_auc_score(y_val, cat_probs):.5f}")
print(f"Ensemble ROC-AUC: {roc_auc_score(y_val, ensemble_probs):.5f}")

LightGBM ROC-AUC: 0.93326
CatBoost ROC-AUC: 0.93929
Ensemble ROC-AUC: 0.93782

In [56]:
import pandas as pd

# 1. Retrain models on full training data
print("Retraining LightGBM on full dataset...")
lgb_model.fit(X, y)

print("Retraining CatBoost on full dataset...")
cat_model.fit(X, y)

# 2. Extract IDs safely (checks if 'id' is in columns or stored in the index)
if 'id' in df_test.columns:
    test_ids = df_test['id']
    X_kaggle_test = df_test.drop(columns=['id', 'Exited'], errors='ignore')
else:
    test_ids = df_test.index
    X_kaggle_test = df_test.drop(columns=['Exited'], errors='ignore')

# 3. Align features with X (ensuring exact same columns and ordering)
X_kaggle_test = X_kaggle_test[X.columns]

# 4. Predict probabilities
lgb_test_probs = lgb_model.predict_proba(X_kaggle_test)[:, 1]
cat_test_probs = cat_model.predict_proba(X_kaggle_test)[:, 1]

# 5. Weighted Ensemble
final_probs = (0.40 * lgb_test_probs) + (0.60 * cat_test_probs)

# 6. Create Submission DataFrame & Save
submission = pd.DataFrame({
    'id': test_ids,
    'Exited': final_probs
})

submission.to_csv('submission.csv', index=False)
print("Saved submission.csv successfully!")
print(submission.head())

Retraining LightGBM on full dataset...
Retraining CatBoost on full dataset...
Saved submission.csv successfully!
   id    Exited
0   0  0.051825
1   1  0.007115
2   2  0.013282
3   3  0.018593
4   4  0.054709

In [57]:
from google.colab import files
files.download('submission.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')