<a href="https://colab.research.google.com/github/Nermeen-Moussa/ML-DL-Reference-Guide/blob/machine-learning/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Supervised Learning algorithm which uses prelabeled data breaks down a dataset into smaller subsets by asking a series of targeted, conditional questions**

**Decision Tree=> we don't need to scale the data , we use it to visualize why we choose the target**




1. Root Node: The very top question that initiates the split on the most critical feature.

2.   Decision (Internal) Nodes: Intermediate checkpoints evaluating specific conditions to further split data.

3.  Leaf (Terminal) Nodes: The endpoints that provide the final classification or numeric prediction.

In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report

Mounted at /content/drive

In [2]:
df=pd.read_csv('/content/drive/MyDrive/500hits.csv',encoding='latin1')

In [3]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Ty Cobb,24,3035,11434,2246,4189,724,295,117,726,1249,357,892,178,0.366,1
1,Stan Musial,22,3026,10972,1949,3630,725,177,475,1951,1599,696,78,31,0.331,1
2,Tris Speaker,22,2789,10195,1882,3514,792,222,117,724,1381,220,432,129,0.345,1
3,Derek Jeter,20,2747,11195,1923,3465,544,66,260,1311,1082,1840,358,97,0.310,1
4,Honus Wagner,21,2792,10430,1736,3430,640,252,101,0,963,327,722,15,0.329,1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   YRS     465 non-null    int64
 1   G       465 non-null    int64
 2   AB      465 non-null    int64
 3   R       465 non-null    int64
 4   H       465 non-null    int64
 5   2B      465 non-null    int64
 6   3B      465 non-null    int64
 7   HR      465 non-null    int64
 8   RBI     465 non-null    int64
 9   BB      465 non-null    int64
 10  SO      465 non-null    int64
 11  SB      465 non-null    int64
 12  BA      465 non-null    float64
 13  HOF     465 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 51.0 KB

In [12]:
df.columns

Index(['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'BA', 'HOF'],
      dtype='object')

In [14]:
X=df.iloc[:,0:13]
y=df.iloc[:,13]

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train,X_test,y_train,y_test.shape

(     YRS     G    AB     R     H   2B  3B   HR   RBI    BB    SO   SB     BA
 46    17  2379  9073  1508  2724  504  80  210  1134  1032  1140  474  0.300
 460   15  1920  6653  1105  1665  285  39  291   964  1224  1427  225  0.250
 117   22  2435  8147  1283  2086  290  24  573  1584  1559  1699   19  0.256
 154   20  2586  9768  1582  2725  565  78  435  1587  1084  1795  312  0.279
 253   19  2084  7218   940  2091  484  66  191  1097   648   779  109  0.290
 ..   ...   ...   ...   ...   ...  ...  ..  ...   ...   ...   ...  ...    ...
 106   22  2588  8197  1229  2211  353  46  521  1555  1345  1550   26  0.270
 270   17  1736  7030  1163  2040  313  98   27     0   439   212  372  0.290
 348   15  1759  6357   851  1861  271  44   85   636   444   609   88  0.293
 435   12  1587  6123   814  1702  308  34  265  1002   331   771   67  0.278
 102   21  2360  7927  1195  2232  423  55  475  1540   937  1936   17  0.282

 [372 rows x 13 columns],
      YRS     G    AB     R     H   2B   3B   HR   RBI    BB    SO   SB     BA
 55    19  2292  7706  1798  2654  525   71  521  1839  2019   709   24  0.344
 75    19  2216  8479  1223  2449  427   78   84   773   606   346   89  0.289
 33    22  2730  9456  1859  2876  488   72  511  1860  1708   896   89  0.304
 456   16  1812  6354  1023  1671  232   50  155   614   833   852  557  0.263
 297   22  2030  6754   990  1977  347   99   95   920   820   598   65  0.293
 ..   ...   ...   ...   ...   ...  ...  ...  ...   ...   ...   ...  ...    ...
 193   18  2194  8136  1098  2303  495   24  386  1417   633  1238   29  0.283
 394   16  1895  6488   864  1774  245   35  382  1119   782  1460    8  0.273
 301   15  1942  6962  1081  1959  432   30  331  1078   874  1622  104  0.281
 22    18  2433  9454  1416  3000  440  166  240  1305   621  1230   83  0.317
 380   17  1852  6292   844  1796  264   62  213   976   561   477   38  0.285

 [93 rows x 13 columns],
 46     1
 460    0
 117    1
 154    0
 253    0
       ..
 106    1
 270    0
 348    0
 435    0
 102    1
 Name: HOF, Length: 372, dtype: int64,
 (93,))

In [18]:
dtc=DecisionTreeClassifier()
dtc.fit(X_train,y_train)
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [21]:
y_pred=dtc.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[54  8]
 [ 7 24]]
              precision    recall  f1-score   support

           0       0.89      0.87      0.88        62
           1       0.75      0.77      0.76        31

    accuracy                           0.84        93
   macro avg       0.82      0.82      0.82        93
weighted avg       0.84      0.84      0.84        93

In [22]:
dtc.feature_importances_

array([0.02061659, 0.03657192, 0.0334831 , 0.3079424 , 0.06333245,
       0.04293532, 0.04819127, 0.0236566 , 0.11806165, 0.05243436,
       0.06213197, 0.03251635, 0.15812602])

In [25]:
features=pd.DataFrame({'Features':X.columns,'Importance':dtc.feature_importances_})
features.head()

  Features  Importance
0      YRS    0.020617
1        G    0.036572
2       AB    0.033483
3        R    0.307942
4        H    0.063332

In [27]:
dct2=DecisionTreeClassifier(criterion='entropy',ccp_alpha=0.04)
dct2.fit(X_train,y_train)
y_pred2=dct2.predict(X_test)
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))
features2=pd.DataFrame({'Features':X.columns,'Importance':dct2.feature_importances_})
features2.head()

[[55  7]
 [11 20]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86        62
           1       0.74      0.65      0.69        31

    accuracy                           0.81        93
   macro avg       0.79      0.77      0.77        93
weighted avg       0.80      0.81      0.80        93

  Features  Importance
0      YRS    0.000000
1        G    0.000000
2       AB    0.000000
3        R    0.553898
4        H    0.000000